#!/bin/zsh
kind create cluster --config kind-config.yaml
kubectl create namespace argocd
cat >argocd/templates/credentials.yaml <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:majordookie/argo-gitops.git
  sshPrivateKey: |
$(while IFS= read -r line; do echo -e "    $line"; done < ~/.ssh/id_rsa)
  insecure: "true" # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
EOF
helm install --namespace argocd argo ./argocd
sleep 30
echo "waiting 30 seconds until argocd is up"
echo "argocd password is..."
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
kubectl apply -f applications.yaml