apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-operator
  namespace: applications
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: couchbase-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://couchbase-partners.github.io/helm-charts/'
    targetRevision: 2.40.1
    chart: couchbase-operator
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
