apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: couchbase-operator
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: 'git@github.com:majordookie/argo-gitops.git'
    path: couchbase-operator
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
