apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:majordookie/argo-gitops.git'
    path: ingress-nginx
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true