spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: HEAD

argocd:
  server:
    ingress:
      enabled: true
couchbase-operator:
  install:
    syncGateway: true